In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('melb_data.csv')

In [6]:
data = data[[ 'Car', 'Landsize' , 'BuildingArea' , 'YearBuilt' , 'Price' ]]
data

       Car  Landsize  BuildingArea  YearBuilt      Price
0      1.0     202.0           NaN        NaN  1480000.0
1      0.0     156.0          79.0     1900.0  1035000.0
2      0.0     134.0         150.0     1900.0  1465000.0
3      1.0      94.0           NaN        NaN   850000.0
4      2.0     120.0         142.0     2014.0  1600000.0
...    ...       ...           ...        ...        ...
13575  2.0     652.0           NaN     1981.0  1245000.0
13576  2.0     333.0         133.0     1995.0  1031000.0
13577  4.0     436.0           NaN     1997.0  1170000.0
13578  5.0     866.0         157.0     1920.0  2500000.0
13579  1.0     362.0         112.0     1920.0  1285000.0

[13580 rows x 5 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           13518 non-null  float64
 1   Landsize      13580 non-null  float64
 2   BuildingArea  7130 non-null   float64
 3   YearBuilt     8205 non-null   float64
 4   Price         13580 non-null  float64
dtypes: float64(5)
memory usage: 530.6 KB

In [8]:
data.isna().sum()

Car               62
Landsize           0
BuildingArea    6450
YearBuilt       5375
Price              0
dtype: int64

In [9]:
data.describe()

                Car       Landsize  BuildingArea    YearBuilt         Price
count  13518.000000   13580.000000   7130.000000  8205.000000  1.358000e+04
mean       1.610075     558.416127    151.967650  1964.684217  1.075684e+06
std        0.962634    3990.669241    541.014538    37.273762  6.393107e+05
min        0.000000       0.000000      0.000000  1196.000000  8.500000e+04
25%        1.000000     177.000000     93.000000  1940.000000  6.500000e+05
50%        2.000000     440.000000    126.000000  1970.000000  9.030000e+05
75%        2.000000     651.000000    174.000000  1999.000000  1.330000e+06
max       10.000000  433014.000000  44515.000000  2018.000000  9.000000e+06

In [11]:
#we are going to use stats method
data['Car'].median()

2.0

In [12]:
data['Car'].fillna(data['Car'].median(),inplace=True)

C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\4177225166.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Car'].fillna(data['Car'].median(),inplace=True)

In [13]:
data['Car']=data['Car'].astype(int)

In [14]:
data['BuildingArea'].median()

126.0

In [15]:
data['BuildingArea'].fillna(data['BuildingArea'].median(),inplace=True )

C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\581110871.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['BuildingArea'].fillna(data['BuildingArea'].median(),inplace=True )

In [19]:
data['YearBuilt'].median()

1970.0

In [20]:
data['YearBuilt'].fillna(data['YearBuilt'].median(),inplace=True )

In [21]:
data['YearBuilt']=data['YearBuilt'].astype(int)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           13580 non-null  int64
 1   Landsize      13580 non-null  float64
 2   BuildingArea  13580 non-null  object
 3   YearBuilt     13580 non-null  int64
 4   Price         13580 non-null  float64
dtypes: float64(2), int64(2), object(1)
memory usage: 530.6+ KB

In [24]:
#Domain Approach
# The usual  car parking alloted to each house as per govt policy is 1
# The Minimum build area for the building as per govt norms is 80
# Maximums buildings as per the census survey was built in year 2000.

In [25]:
data1 = pd.read_csv('melb_data.csv')
dataDomain = data1[[ 'Car', 'Landsize' , 'BuildingArea' , 'YearBuilt' , 'Price' ]]

In [26]:
# The usual  car parking alloted to each house as per govt policy is 1
# The Minimum build area for the building as per govt norms is 80
# Maximums buildings as per the census survey was built in year 2000.

In [27]:
dataDomain['Car'].fillna(1 , inplace=True)

C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\423013024.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataDomain['Car'].fillna(1 , inplace=True)
C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\423013024.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataDomain['Car'].fillna(1 , inplace=True)

In [28]:
dataDomain['BuildingArea'].fillna(80 , inplace=True)

C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\2036782825.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataDomain['BuildingArea'].fillna(80 , inplace=True)
C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\2036782825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataDomain['BuildingArea'].fillna(80 , inplace=True)

In [29]:
dataDomain['YearBuilt'].fillna(2000, inplace=True)

C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\3767384647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataDomain['YearBuilt'].fillna(2000, inplace=True)
C:\Users\shrid\AppData\Local\Temp\ipykernel_20348\3767384647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataDomain['YearBuilt'].fillna(2000, inplace=True)

In [30]:
dataDomain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           13580 non-null  float64
 1   Landsize      13580 non-null  float64
 2   BuildingArea  13580 non-null  float64
 3   YearBuilt     13580 non-null  float64
 4   Price         13580 non-null  float64
dtypes: float64(5)
memory usage: 530.6 KB