In [1]:
#Handling Ordinal Data
# Ordinal Data is categorical data with ranking
# Dealing with ordinal data, you can use Ordinal Encoding
# Ordinal Encoding means
#    - Replace Category with its associated rank
#    - Replace Category with the index location of unique value

In [3]:
import pandas as pd

In [4]:
data2 = {
    'Satisfaction': ['Neutral','Satisfied','Very Satisfied','Dissatisfied', 'Very Dissatisfied','Neutral']
}
df = pd.DataFrame(data2)
df

        Satisfaction
0            Neutral
1          Satisfied
2     Very Satisfied
3       Dissatisfied
4  Very Dissatisfied
5            Neutral

In [5]:
mapping = {"Very Dissatisfied": 0,
"Dissatisfied": 1,
           "Neutral": 2,
           "Satisfied": 3,
           "Very Satisfied": 4}

df['SatisfactionEncoded'] = df['Satisfaction'].map(mapping)
df

        Satisfaction  SatisfactionEncoded
0            Neutral                    2
1          Satisfied                    3
2     Very Satisfied                    4
3       Dissatisfied                    1
4  Very Dissatisfied                    0
5            Neutral                    2