In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
data = pd.read_csv("50_Startups.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
# Performing Hypothesis Testing
#
# 1. Create a Viable Question Goal (The question must result in a Binary Outcome)
# 2. Convert the question goal into Hypothesis (h0 and h1)
# 3. Select the Statistical Testing Formula to Validate the Hypothesis (Check who wins?)
# 4. Select/Determine SL of the Project
# 5. Calc the p-value using Statistical Testing formula and compare the same with the SL to check who wins
#
#

In [6]:
# TEST FOR FEATURE ELIMINATION | Feature Comparison (In terms of Inferential Stats | Model Training | Model Building)
#
# Compare two column/variables to check if they are statistically similar
#
#                                     Test for Feature Elimination
#                                                |
#      -------------------------------------------------------------------------------------------
#      |                                                                                         |
#  Numerical and Numerical Pair                           Numerical and Categorical Pair | Categorical and Categorical
#       |
#   ----------------------------------------
#.  |                                      |
# if both pass Normality Test      if both fail Normality Test | if one of them fail normality
#   use Parametric test              use Non-parametric Test
#
#
# if col1 and col2 are Normally Dist:
#          Use Parametric Test to Identify whether to preserve or eliminate col
# else:
#          Use Non-Parametric Test to Identify whether to preserve or eliminate col
#
#
# Formulate the Hypothesis
#
# h0 --------- Eliminate one of the variable
# ha --------- Preserve both variable

In [7]:
# Goal: Check if RDSPend and Admin Spend is Statistically Significant | similar | twins
#
# Step1: Check if RDSpend and AdminSpend is Normally Distributed using Shapiro test

In [8]:
SL = 0.05

from scipy.stats import shapiro

stat, p = shapiro(data["R&D Spend"])

if p >= SL:
  print("ALternate Hypothesis (Ha) ---- RDSpend is Normally Dist")
else:
  print("Null Hypothesis (H0) ---- RDSpend is Not Normally Dist")

ALternate Hypothesis (Ha) ---- RDSpend is Normally Dist

In [9]:
SL = 0.05

from scipy.stats import shapiro

stat, p = shapiro(data["Administration"])

if p >= SL:
  print("ALternate Hypothesis (Ha) ---- Administration is Normally Dist")
else:
  print("Null Hypothesis (H0) ---- Administration is Not Normally Dist")

ALternate Hypothesis (Ha) ---- Administration is Normally Dist

In [10]:
# Goal: Check if RDSPend and Admin Spend is Statistically Significant | similar | twins

# 1. Create a viable question goal
#
# Check if RDSpend and Admin are Statistically Same
#
# 2. Convert the question into Hypothesis
#
#  H0 -------- RDSpend and AdminSpend are Statistically Same. Therefore eliminate one of them
#  H1 -------- RDSpend and Admin are Statistically Different. Therefore Preserve both of them
#
# 3. Select Test
#
#     Student T Test
#
# 4. Select SL
#
#      0.05
#
# 5. Calc p value

SL = 0.05

from scipy.stats import ttest_ind

stat, p = ttest_ind(data["R&D Spend"], data["Administration"])

if p <= SL:
  print("Alternate Hypothesis (H1) ---- RDSpend and Admin are Statistically Different. Therefore Preserve both of them")
else:
  print("Null Hypothesis (H0) --RDSpend and AdminSpend are Statistically Same. Therefore eliminate one of them")

Alternate Hypothesis (H1) ---- RDSpend and Admin are Statistically Different. Therefore Preserve both of them

# Chi-Square Test

In [11]:
# Chi-square for Feature Elimination
#
# It is meant to deeal with Feature(independent Variable) and Label(dependent variable) pair
#
# 1. Feature is categorical and label is numerical
# 2. Feature is categorical and label is categorical
# 3. Feature is numerical and label is categorical
#
# The goal this test is to check whether there exists any kind of STATISTICAL RELATIONSHIP between two columns

In [12]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [13]:
#Check if State and Profit have any Stat relationship
# Contigency Table | Pivot Table

ct = pd.crosstab(data["State"], data["Profit"])
ct

Profit,14681.40,35673.41,42559.73,49490.75,64926.08,65200.33,69758.98,71498.49,77798.83,78239.91,...,149759.96,152211.77,155752.60,156122.51,156991.12,166187.94,182901.99,191050.39,191792.06,192261.83
State,,,,,,,,,,,,,,,,,,,,,
California,1,0,1,0,0,1,0,1,0,1,...,1,0,0,1,0,0,0,0,1,0
Florida,0,0,0,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
New York,0,1,0,0,1,0,1,0,0,0,...,0,1,0,0,1,0,1,0,0,1

In [14]:
# from scipy.stats import chi2_contingency
# ?chi2_contingency

In [15]:
SL = 0.05

from scipy.stats import chi2_contingency

_,pvalue,_,_ = chi2_contingency(ct)

if pvalue <= SL:
  print("Alternate Hypothesis (H1) ---- State and Profit has some Statistical Relationship. Thus Preserve State column")
else:
  print("Null Hypothesis (H0)------ State and Profit has NO Statistical Relationship. Thus Eliminate State column")

Null Hypothesis (H0)------ State and Profit has NO Statistical Relationship. Thus Eliminate State column